server:
  port: 10080
spring:
  application:
    name: config-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JerryDtj/springCloud.git
#          search-paths: config-repo